name: Docker Image CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to the docker repository
      env: 
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }} 
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
         docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        
    - name: Building the Docker image
      run: |
        COMMIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
        docker build -t ${{ secrets.DOCKER_USERNAME }}/tsg-server:$COMMIT_SHA ./backend
        docker tag ${{ secrets.DOCKER_USERNAME }}/tsg-server:$COMMIT_SHA ${{ secrets.DOCKER_USERNAME }}/tsg-server:$COMMIT_SHA

    - name: Push image to docker
      run: |
        COMMIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
        docker push ${{ secrets.DOCKER_USERNAME }}/tsg-server:$COMMIT_SHA ${{ secrets.DOCKER_USERNAME }}/tsg-server:$COMMIT_SHA
